FROM apache/airflow:2.11.2-python3.11

USER root

RUN apt-get update \
    && apt-get install --yes --no-install-recommends openjdk-17-jre-headless procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

COPY requirements.txt /tmp/data-platform-requirements.txt

USER airflow

RUN pip install --no-cache-dir --requirement /tmp/data-platform-requirements.txt \
    && pip check
