from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    TimestampType,
    DateType,
    LongType,
    DoubleType,
    IntegerType,
    DecimalType,
    BooleanType,
)

ingestion_log_schema = StructType(
    [
        StructField("run_id", StringType(), False),
        StructField("source_name", StringType(), True),
        StructField("source_table", StringType(), True),
        StructField("source_type", StringType(), True),
        StructField("file_name", StringType(), True),
        StructField("target_path", StringType(), True),
        StructField("started_at", TimestampType(), True),
        StructField("ended_at", TimestampType(), True),
        StructField("duration_seconds", DoubleType(), True),
        StructField("execution_status", StringType(), True),
        StructField("error_message", StringType(), True),
        StructField("execution_date", DateType(), True),
    ]
)

landing_quality_log_schema = StructType(
    [
        StructField("run_id", StringType(), False),
        StructField("file_name", StringType(), True),
        StructField("source_name", StringType(), True),
        StructField("file_path", StringType(), True),
        StructField("check_name", StringType(), True),
        StructField("check_type", StringType(), True),
        StructField("records_total", LongType(), True),
        StructField("records_valid", LongType(), True),
        StructField("records_invalid", LongType(), True),
        StructField("invalid_percentage", DoubleType(), True),
        StructField("check_status", StringType(), True),
        StructField("error_message", StringType(), True),
        StructField("execution_ts", TimestampType(), True),
    ]
)

data_correction_log_schema = StructType(
    [
        StructField("correction_run_id", StringType(), False),
        StructField("original_run_id", StringType(), True),
        StructField("dataset_name", StringType(), True),
        StructField("source_name", StringType(), True),
        StructField("file_name", StringType(), True),
        StructField("original_path", StringType(), True),
        StructField("target_path", StringType(), True),
        StructField("correction_type", StringType(), True),
        StructField("records_input", LongType(), True),
        StructField("records_corrected", LongType(), True),
        StructField("records_still_invalid", LongType(), True),
        StructField("records_discarded", LongType(), True),
        StructField("correction_attempt", IntegerType(), True),
        StructField("correction_status", StringType(), True),
        StructField("error_message", StringType(), True),
        StructField("correction_start_ts", TimestampType(), True),
        StructField("correction_end_ts", TimestampType(), True),
        StructField("duration_seconds", DoubleType(), True),
        StructField("execution_date", DateType(), True),
    ]
)

transformation_log_schema = StructType(
    [
        StructField("run_id", StringType(), False),
        StructField("pipeline_name", StringType(), True),
        StructField("stage", StringType(), True),
        StructField("source_table", StringType(), True),
        StructField("target_table", StringType(), True),
        StructField("source_path", StringType(), True),
        StructField("target_path", StringType(), True),
        StructField("records_input", LongType(), True),
        StructField("records_output", LongType(), True),
        StructField("records_rejected", LongType(), True),
        StructField("records_inserted", LongType(), True),
        StructField("records_updated", LongType(), True),
        StructField("records_deleted", LongType(), True),
        StructField("data_quality_status", StringType(), True),
        StructField("processing_start_ts", TimestampType(), True),
        StructField("processing_end_ts", TimestampType(), True),
        StructField("duration_seconds", DoubleType(), True),
        StructField("status", StringType(), True),
        StructField("error_message", StringType(), True),
        StructField("execution_date", DateType(), True),
    ]
)

gold_validation_failure_schema = StructType(
    [
        StructField("run_id", StringType(), False),
        StructField("datamart", StringType(), False),
        StructField("validation_type", StringType(), False),
        StructField("validation_error", StringType(), False),
        StructField("candidate_tables", StringType(), True),
        StructField("validation_status", StringType(), False),
        StructField("execution_ts", TimestampType(), False),
        StructField("execution_date", DateType(), False),
    ]
)

ingestion_watermark_schema = StructType(
    [
        StructField("source_name", StringType(), False),
        StructField("dataset_name", StringType(), False),
        StructField("watermark_ts", TimestampType(), False),
        StructField("last_successful_run_id", StringType(), False),
        StructField("committed_at", TimestampType(), False),
    ]
)

BRONZE_DATASET_SCHEMAS = {
    "coupons": StructType(
        [
            StructField("coupon", StringType(), True),
            StructField("description", StringType(), True),
            StructField("discount", DecimalType(14, 2), True),
            StructField("discount_type", StringType(), True),
            StructField("currency", StringType(), True),
            StructField("minimum_order_amount", DecimalType(16, 2), True),
            StructField("maximum_discount_amount", DecimalType(16, 2), True),
            StructField("usage_limit", IntegerType(), True),
            StructField("usage_limit_per_customer", IntegerType(), True),
            StructField("is_active", BooleanType(), True),
            StructField("start_date", DateType(), True),
            StructField("end_date", DateType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "delivery_tracking": StructType(
        [
            StructField("tracking_id", LongType(), True),
            StructField("order_id", LongType(), True),
            StructField("shipment_id", LongType(), True),
            StructField("tracking_code", StringType(), True),
            StructField("carrier", StringType(), True),
            StructField("service_level", StringType(), True),
            StructField("status", StringType(), True),
            StructField("event_description", StringType(), True),
            StructField("city", StringType(), True),
            StructField("state", StringType(), True),
            StructField("country_code", StringType(), True),
            StructField("estimated_delivery_at", TimestampType(), True),
            StructField("occurred_at", TimestampType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "payments": StructType(
        [
            StructField("payment_id", LongType(), True),
            StructField("order_id", LongType(), True),
            StructField("transaction_reference", StringType(), True),
            StructField("payment_method", StringType(), True),
            StructField("payment_status", StringType(), True),
            StructField("amount", DecimalType(16, 2), True),
            StructField("currency", StringType(), True),
            StructField("installments", IntegerType(), True),
            StructField("provider", StringType(), True),
            StructField("authorized_at", TimestampType(), True),
            StructField("paid_at", TimestampType(), True),
            StructField("refunded_amount", DecimalType(16, 2), True),
            StructField("failure_code", StringType(), True),
            StructField("failure_reason", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "website_events": StructType(
        [
            StructField("event_id", LongType(), True),
            StructField("customer_id", LongType(), True),
            StructField("anonymous_id", StringType(), True),
            StructField("session_id", StringType(), True),
            StructField("event", StringType(), True),
            StructField("page", StringType(), True),
            StructField("timestamp", TimestampType(), True),
            StructField("product_id", LongType(), True),
            StructField("order_id", LongType(), True),
            StructField("device_type", StringType(), True),
            StructField("browser", StringType(), True),
            StructField("operating_system", StringType(), True),
            StructField("traffic_source", StringType(), True),
            StructField("utm_source", StringType(), True),
            StructField("utm_medium", StringType(), True),
            StructField("utm_campaign", StringType(), True),
            StructField("country_code", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "customer_review": StructType(
        [
            StructField("review_id", LongType(), True),
            StructField("customer_id", LongType(), True),
            StructField("product_id", LongType(), True),
            StructField("order_id", LongType(), True),
            StructField("rating", IntegerType(), True),
            StructField("title", StringType(), True),
            StructField("comment", StringType(), True),
            StructField("verified_purchase", BooleanType(), True),
            StructField("moderation_status", StringType(), True),
            StructField("helpful_votes", IntegerType(), True),
            StructField("language", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "exchange_rates": StructType(
        [
            StructField("exchange_rate_id", LongType(), True),
            StructField("date", DateType(), True),
            StructField("base_currency", StringType(), True),
            StructField("usd_brl", DecimalType(12, 6), True),
            StructField("eur_brl", DecimalType(12, 6), True),
            StructField("provider", StringType(), True),
            StructField("rate_type", StringType(), True),
            StructField("published_at", TimestampType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "marketing_campaigns": StructType(
        [
            StructField("campaign_id", LongType(), True),
            StructField("campaign", StringType(), True),
            StructField("channel", StringType(), True),
            StructField("objective", StringType(), True),
            StructField("status", StringType(), True),
            StructField("budget", DecimalType(16, 2), True),
            StructField("actual_spend", DecimalType(16, 2), True),
            StructField("currency", StringType(), True),
            StructField("start_date", DateType(), True),
            StructField("end_date", DateType(), True),
            StructField("target_audience", StringType(), True),
            StructField("utm_source", StringType(), True),
            StructField("utm_medium", StringType(), True),
            StructField("utm_campaign", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "customers": StructType(
        [
            StructField("customer_id", LongType(), True),
            StructField("name", StringType(), True),
            StructField("email", StringType(), True),
            StructField("phone", StringType(), True),
            StructField("customer_type", StringType(), True),
            StructField("tax_id", StringType(), True),
            StructField("birth_date", DateType(), True),
            StructField("address_line", StringType(), True),
            StructField("postal_code", StringType(), True),
            StructField("city", StringType(), True),
            StructField("state", StringType(), True),
            StructField("country_code", StringType(), True),
            StructField("acquisition_channel", StringType(), True),
            StructField("marketing_opt_in", BooleanType(), True),
            StructField("status", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "products": StructType(
        [
            StructField("product_id", LongType(), True),
            StructField("sku", StringType(), True),
            StructField("barcode", StringType(), True),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("category", StringType(), True),
            StructField("subcategory", StringType(), True),
            StructField("brand", StringType(), True),
            StructField("supplier_id", LongType(), True),
            StructField("price", DecimalType(14, 2), True),
            StructField("cost_price", DecimalType(14, 2), True),
            StructField("currency", StringType(), True),
            StructField("weight_kg", DecimalType(10, 3), True),
            StructField("height_cm", DecimalType(10, 2), True),
            StructField("width_cm", DecimalType(10, 2), True),
            StructField("length_cm", DecimalType(10, 2), True),
            StructField("is_active", BooleanType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "suppliers": StructType(
        [
            StructField("supplier_id", LongType(), True),
            StructField("supplier_code", StringType(), True),
            StructField("supplier_name", StringType(), True),
            StructField("legal_name", StringType(), True),
            StructField("tax_id", StringType(), True),
            StructField("contact_name", StringType(), True),
            StructField("email", StringType(), True),
            StructField("phone", StringType(), True),
            StructField("address_line", StringType(), True),
            StructField("postal_code", StringType(), True),
            StructField("city", StringType(), True),
            StructField("state", StringType(), True),
            StructField("country_code", StringType(), True),
            StructField("payment_terms_days", IntegerType(), True),
            StructField("lead_time_days", IntegerType(), True),
            StructField("is_active", BooleanType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "inventory": StructType(
        [
            StructField("inventory_id", LongType(), True),
            StructField("product_id", LongType(), True),
            StructField("warehouse_code", StringType(), True),
            StructField("bin_location", StringType(), True),
            StructField("quantity_available", IntegerType(), True),
            StructField("quantity_reserved", IntegerType(), True),
            StructField("quantity_damaged", IntegerType(), True),
            StructField("reorder_point", IntegerType(), True),
            StructField("safety_stock", IntegerType(), True),
            StructField("last_restocked_at", TimestampType(), True),
            StructField("last_counted_at", TimestampType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "order_items": StructType(
        [
            StructField("order_item_id", LongType(), True),
            StructField("order_id", LongType(), True),
            StructField("line_number", IntegerType(), True),
            StructField("product_id", LongType(), True),
            StructField("sku", StringType(), True),
            StructField("product_name", StringType(), True),
            StructField("quantity", IntegerType(), True),
            StructField("unit_price", DecimalType(14, 2), True),
            StructField("discount_amount", DecimalType(16, 2), True),
            StructField("tax_amount", DecimalType(16, 2), True),
            StructField("line_total", DecimalType(16, 2), True),
            StructField("currency", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
    "orders": StructType(
        [
            StructField("order_id", LongType(), True),
            StructField("order_number", StringType(), True),
            StructField("customer_id", LongType(), True),
            StructField("order_date", TimestampType(), True),
            StructField("status", StringType(), True),
            StructField("sales_channel", StringType(), True),
            StructField("currency", StringType(), True),
            StructField("subtotal_amount", DecimalType(16, 2), True),
            StructField("discount_amount", DecimalType(16, 2), True),
            StructField("shipping_amount", DecimalType(16, 2), True),
            StructField("tax_amount", DecimalType(16, 2), True),
            StructField("total_amount", DecimalType(16, 2), True),
            StructField("coupon_code", StringType(), True),
            StructField("shipping_recipient", StringType(), True),
            StructField("shipping_address_line", StringType(), True),
            StructField("shipping_postal_code", StringType(), True),
            StructField("shipping_city", StringType(), True),
            StructField("shipping_state", StringType(), True),
            StructField("shipping_country_code", StringType(), True),
            StructField("delivered_at", TimestampType(), True),
            StructField("cancelled_at", TimestampType(), True),
            StructField("cancellation_reason", StringType(), True),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
        ]
    ),
}

DATASET_REQUIRED_FIELDS = {
    "coupons": ["coupon", "discount", "discount_type", "currency", "minimum_order_amount", "is_active", "start_date", "end_date", "created_at", "updated_at"],
    "delivery_tracking": ["tracking_id", "order_id", "shipment_id", "tracking_code", "carrier", "service_level", "status", "country_code", "occurred_at", "created_at", "updated_at"],
    "payments": ["payment_id", "order_id", "transaction_reference", "payment_method", "payment_status", "amount", "currency", "installments", "provider", "refunded_amount", "created_at", "updated_at"],
    "website_events": ["event_id", "session_id", "event", "page", "timestamp", "created_at", "updated_at"],
    "customer_review": ["review_id", "customer_id", "product_id", "rating", "verified_purchase", "moderation_status", "created_at", "updated_at"],
    "exchange_rates": ["exchange_rate_id", "date", "base_currency", "usd_brl", "eur_brl", "provider", "published_at", "created_at", "updated_at"],
    "marketing_campaigns": ["campaign_id", "campaign", "channel", "status", "budget", "currency", "start_date", "end_date", "created_at", "updated_at"],
    "customers": ["customer_id", "name", "email", "customer_type", "country_code", "marketing_opt_in", "status", "created_at", "updated_at"],
    "products": ["product_id", "sku", "name", "category", "supplier_id", "price", "currency", "is_active", "created_at", "updated_at"],
    "suppliers": ["supplier_id", "supplier_code", "supplier_name", "country_code", "payment_terms_days", "is_active", "created_at", "updated_at"],
    "inventory": ["inventory_id", "product_id", "warehouse_code", "quantity_available", "quantity_reserved", "quantity_damaged", "reorder_point", "safety_stock", "created_at", "updated_at"],
    "order_items": ["order_item_id", "order_id", "line_number", "product_id", "sku", "product_name", "quantity", "unit_price", "discount_amount", "tax_amount", "line_total", "currency", "created_at", "updated_at"],
    "orders": ["order_id", "order_number", "customer_id", "order_date", "status", "sales_channel", "currency", "subtotal_amount", "discount_amount", "shipping_amount", "tax_amount", "total_amount", "shipping_recipient", "shipping_address_line", "shipping_postal_code", "shipping_city", "shipping_state", "shipping_country_code", "created_at", "updated_at"],
}

DATASET_PRIMARY_KEYS = {
    "coupons": ["coupon"],
    "delivery_tracking": ["tracking_id"],
    "payments": ["payment_id"],
    "website_events": ["event_id"],
    "customer_review": ["review_id"],
    "exchange_rates": ["exchange_rate_id"],
    "marketing_campaigns": ["campaign_id"],
    "customers": ["customer_id"],
    "products": ["product_id"],
    "suppliers": ["supplier_id"],
    "inventory": ["inventory_id"],
    "order_items": ["order_item_id"],
    "orders": ["order_id"],
}
