from decimal import Decimal

DATABASE_NAME = "data_platform"

POSTGRES_DDL = {'suppliers': 'CREATE TABLE public.suppliers (\n'
              '    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n'
              '    supplier_code VARCHAR(30) NOT NULL UNIQUE,\n'
              '    supplier_name VARCHAR(160) NOT NULL,\n'
              '    legal_name VARCHAR(200),\n'
              '    tax_id VARCHAR(30),\n'
              '    contact_name VARCHAR(120),\n'
              '    email VARCHAR(254),\n'
              '    phone VARCHAR(30),\n'
              '    address_line VARCHAR(200),\n'
              '    postal_code VARCHAR(20),\n'
              '    city VARCHAR(100),\n'
              '    state VARCHAR(50),\n'
              "    country_code CHAR(2) NOT NULL DEFAULT 'BR',\n"
              '    payment_terms_days INTEGER NOT NULL DEFAULT 30 CHECK (payment_terms_days >= 0),\n'
              '    lead_time_days INTEGER CHECK (lead_time_days >= 0),\n'
              '    is_active BOOLEAN NOT NULL DEFAULT TRUE,\n'
              '    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,\n'
              '    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,\n'
              '    CHECK (updated_at >= created_at)\n'
              ');\n'
              'CREATE INDEX idx_suppliers_created ON public.suppliers (created_at, supplier_id);\n'
              'CREATE INDEX idx_suppliers_updated ON public.suppliers (updated_at, supplier_id);\n',
 'customers': 'CREATE TABLE public.customers (\n'
              '    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n'
              '    name VARCHAR(160) NOT NULL,\n'
              '    email VARCHAR(254) NOT NULL UNIQUE,\n'
              '    phone VARCHAR(30),\n'
              "    customer_type VARCHAR(20) NOT NULL DEFAULT 'individual'\n"
              "        CHECK (customer_type IN ('individual', 'business')),\n"
              '    tax_id VARCHAR(30),\n'
              '    birth_date DATE,\n'
              '    address_line VARCHAR(200),\n'
              '    postal_code VARCHAR(20),\n'
              '    city VARCHAR(100),\n'
              '    state VARCHAR(50),\n'
              "    country_code CHAR(2) NOT NULL DEFAULT 'BR',\n"
              '    acquisition_channel VARCHAR(50),\n'
              '    marketing_opt_in BOOLEAN NOT NULL DEFAULT FALSE,\n'
              "    status VARCHAR(20) NOT NULL DEFAULT 'active'\n"
              "        CHECK (status IN ('active', 'inactive', 'blocked')),\n"
              '    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,\n'
              '    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,\n'
              '    CHECK (updated_at >= created_at)\n'
              ');\n'
              'CREATE INDEX idx_customers_created ON public.customers (created_at, customer_id);\n'
              'CREATE INDEX idx_customers_updated ON public.customers (updated_at, customer_id);\n',
 'products': 'CREATE TABLE public.products (\n'
             '    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n'
             '    sku VARCHAR(50) NOT NULL UNIQUE,\n'
             '    barcode VARCHAR(14),\n'
             '    name VARCHAR(200) NOT NULL,\n'
             '    description TEXT,\n'
             '    category VARCHAR(100) NOT NULL,\n'
             '    subcategory VARCHAR(100),\n'
             '    brand VARCHAR(100),\n'
             '    supplier_id BIGINT NOT NULL REFERENCES public.suppliers (supplier_id),\n'
             '    price NUMERIC(14, 2) NOT NULL CHECK (price >= 0),\n'
             '    cost_price NUMERIC(14, 2) CHECK (cost_price >= 0),\n'
             "    currency CHAR(3) NOT NULL DEFAULT 'BRL',\n"
             '    weight_kg NUMERIC(10, 3) CHECK (weight_kg >= 0),\n'
             '    height_cm NUMERIC(10, 2) CHECK (height_cm >= 0),\n'
             '    width_cm NUMERIC(10, 2) CHECK (width_cm >= 0),\n'
             '    length_cm NUMERIC(10, 2) CHECK (length_cm >= 0),\n'
             '    is_active BOOLEAN NOT NULL DEFAULT TRUE,\n'
             '    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,\n'
             '    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,\n'
             '    CHECK (updated_at >= created_at)\n'
             ');\n'
             'CREATE INDEX idx_products_supplier ON public.products (supplier_id);\n'
             'CREATE INDEX idx_products_created ON public.products (created_at, product_id);\n'
             'CREATE INDEX idx_products_updated ON public.products (updated_at, product_id);\n'}

MYSQL_DDL = {'orders': "CREATE TABLE orders (\n    order_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,\n    order_number VARCHAR(40) NOT NULL UNIQUE,\n    customer_id BIGINT NOT NULL,\n    order_date DATETIME(6) NOT NULL,\n    status VARCHAR(20) NOT NULL DEFAULT 'pending',\n    sales_channel VARCHAR(30) NOT NULL,\n    currency CHAR(3) NOT NULL DEFAULT 'BRL',\n    subtotal_amount DECIMAL(16, 2) NOT NULL,\n    discount_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,\n    shipping_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,\n    tax_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,\n    total_amount DECIMAL(16, 2) NOT NULL,\n    coupon_code VARCHAR(40),\n    shipping_recipient VARCHAR(160) NOT NULL,\n    shipping_address_line VARCHAR(200) NOT NULL,\n    shipping_postal_code VARCHAR(20) NOT NULL,\n    shipping_city VARCHAR(100) NOT NULL,\n    shipping_state VARCHAR(50) NOT NULL,\n    shipping_country_code CHAR(2) NOT NULL DEFAULT 'BR',\n    delivered_at DATETIME(6),\n    cancelled_at DATETIME(6),\n    cancellation_reason VARCHAR(250),\n    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n    CHECK (status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded')),\n    CHECK (subtotal_amount >= 0 AND discount_amount >= 0 AND shipping_amount >= 0 AND tax_amount >= 0),\n    CHECK (total_amount = subtotal_amount - discount_amount + shipping_amount + tax_amount AND total_amount >= 0),\n    CHECK (updated_at >= created_at),\n    INDEX idx_orders_customer (customer_id),\n    INDEX idx_orders_created (created_at, order_id),\n    INDEX idx_orders_updated (updated_at, order_id)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n",
 'order_items': 'CREATE TABLE order_items (\n'
                '    order_item_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,\n'
                '    order_id BIGINT NOT NULL,\n'
                '    line_number INT NOT NULL,\n'
                '    product_id BIGINT NOT NULL,\n'
                '    sku VARCHAR(50) NOT NULL,\n'
                '    product_name VARCHAR(200) NOT NULL,\n'
                '    quantity INT NOT NULL,\n'
                '    unit_price DECIMAL(14, 2) NOT NULL,\n'
                '    discount_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,\n'
                '    tax_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,\n'
                '    line_total DECIMAL(16, 2) NOT NULL,\n'
                "    currency CHAR(3) NOT NULL DEFAULT 'BRL',\n"
                '    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n'
                '    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE '
                'CURRENT_TIMESTAMP(6),\n'
                '    UNIQUE (order_id, line_number),\n'
                '    FOREIGN KEY (order_id) REFERENCES orders (order_id),\n'
                '    CHECK (quantity > 0 AND line_number > 0),\n'
                '    CHECK (unit_price >= 0 AND discount_amount >= 0 AND tax_amount >= 0),\n'
                '    CHECK (line_total = quantity * unit_price - discount_amount + tax_amount AND line_total '
                '>= 0),\n'
                '    CHECK (updated_at >= created_at),\n'
                '    INDEX idx_order_items_product (product_id),\n'
                '    INDEX idx_order_items_created (created_at, order_item_id),\n'
                '    INDEX idx_order_items_updated (updated_at, order_item_id)\n'
                ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n',
 'inventory': 'CREATE TABLE inventory (\n'
              '    inventory_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,\n'
              '    product_id BIGINT NOT NULL,\n'
              '    warehouse_code VARCHAR(30) NOT NULL,\n'
              '    bin_location VARCHAR(50),\n'
              '    quantity_available INT NOT NULL DEFAULT 0,\n'
              '    quantity_reserved INT NOT NULL DEFAULT 0,\n'
              '    quantity_damaged INT NOT NULL DEFAULT 0,\n'
              '    reorder_point INT NOT NULL DEFAULT 0,\n'
              '    safety_stock INT NOT NULL DEFAULT 0,\n'
              '    last_restocked_at DATETIME(6),\n'
              '    last_counted_at DATETIME(6),\n'
              '    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n'
              '    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE '
              'CURRENT_TIMESTAMP(6),\n'
              '    UNIQUE (product_id, warehouse_code),\n'
              '    CHECK (quantity_available >= 0 AND quantity_reserved >= 0 AND quantity_damaged >= 0),\n'
              '    CHECK (reorder_point >= 0 AND safety_stock >= 0),\n'
              '    CHECK (updated_at >= created_at),\n'
              '    INDEX idx_inventory_created (created_at, inventory_id),\n'
              '    INDEX idx_inventory_updated (updated_at, inventory_id)\n'
              ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n'}

CSV_HEADERS = {'coupons': ['coupon',
             'description',
             'discount',
             'discount_type',
             'currency',
             'minimum_order_amount',
             'maximum_discount_amount',
             'usage_limit',
             'usage_limit_per_customer',
             'is_active',
             'start_date',
             'end_date',
             'created_at',
             'updated_at'],
 'delivery_tracking': ['tracking_id',
                       'order_id',
                       'shipment_id',
                       'tracking_code',
                       'carrier',
                       'service_level',
                       'status',
                       'event_description',
                       'city',
                       'state',
                       'country_code',
                       'estimated_delivery_at',
                       'occurred_at',
                       'created_at',
                       'updated_at'],
 'payments': ['payment_id',
              'order_id',
              'transaction_reference',
              'payment_method',
              'payment_status',
              'amount',
              'currency',
              'installments',
              'provider',
              'authorized_at',
              'paid_at',
              'refunded_amount',
              'failure_code',
              'failure_reason',
              'created_at',
              'updated_at']}

JSON_SCHEMAS = {'customer_reviews': {'$schema': 'https://json-schema.org/draft/2020-12/schema',
                      'title': 'api_customer_reviews',
                      'description': 'Contrato estrutural; sem registros.',
                      'type': 'array',
                      'items': {'type': 'object',
                                'additionalProperties': False,
                                'required': ['review_id',
                                             'customer_id',
                                             'product_id',
                                             'rating',
                                             'verified_purchase',
                                             'moderation_status',
                                             'created_at',
                                             'updated_at'],
                                'properties': {'review_id': {'type': 'integer', 'minimum': 1},
                                               'customer_id': {'type': 'integer', 'minimum': 1},
                                               'product_id': {'type': 'integer', 'minimum': 1},
                                               'order_id': {'type': ['integer', 'null'], 'minimum': 1},
                                               'rating': {'type': 'integer', 'minimum': 1, 'maximum': 5},
                                               'title': {'type': ['string', 'null']},
                                               'comment': {'type': ['string', 'null']},
                                               'verified_purchase': {'type': 'boolean'},
                                               'moderation_status': {'type': 'string'},
                                               'helpful_votes': {'type': ['integer', 'null'], 'minimum': 0},
                                               'language': {'type': ['string', 'null']},
                                               'created_at': {'type': 'string',
                                                              'format': 'date-time',
                                                              'pattern': 'Z$'},
                                               'updated_at': {'type': 'string',
                                                              'format': 'date-time',
                                                              'pattern': 'Z$'}}}},
 'exchange_rates': {'$schema': 'https://json-schema.org/draft/2020-12/schema',
                    'title': 'api_exchange_rates',
                    'description': 'Contrato estrutural; sem registros.',
                    'type': 'array',
                    'items': {'type': 'object',
                              'additionalProperties': False,
                              'required': ['exchange_rate_id',
                                           'date',
                                           'base_currency',
                                           'usd_brl',
                                           'eur_brl',
                                           'provider',
                                           'published_at',
                                           'created_at',
                                           'updated_at'],
                              'properties': {'exchange_rate_id': {'type': 'integer', 'minimum': 1},
                                             'date': {'type': 'string', 'format': 'date'},
                                             'base_currency': {'type': 'string',
                                                               'pattern': '^[A-Z]{3}$',
                                                               'const': 'BRL'},
                                             'usd_brl': {'type': 'number',
                                                         'exclusiveMinimum': 0,
                                                         'multipleOf': Decimal('0.000001')},
                                             'eur_brl': {'type': 'number',
                                                         'exclusiveMinimum': 0,
                                                         'multipleOf': Decimal('0.000001')},
                                             'provider': {'type': 'string'},
                                             'rate_type': {'type': ['string', 'null']},
                                             'published_at': {'type': 'string',
                                                              'format': 'date-time',
                                                              'pattern': 'Z$'},
                                             'created_at': {'type': 'string',
                                                            'format': 'date-time',
                                                            'pattern': 'Z$'},
                                             'updated_at': {'type': 'string',
                                                            'format': 'date-time',
                                                            'pattern': 'Z$'}}}},
 'marketing_campaigns': {'$schema': 'https://json-schema.org/draft/2020-12/schema',
                         'title': 'api_marketing_campaigns',
                         'description': 'Contrato estrutural; sem registros.',
                         'type': 'array',
                         'items': {'type': 'object',
                                   'additionalProperties': False,
                                   'required': ['campaign_id',
                                                'campaign',
                                                'channel',
                                                'status',
                                                'budget',
                                                'currency',
                                                'start_date',
                                                'end_date',
                                                'created_at',
                                                'updated_at'],
                                   'properties': {'campaign_id': {'type': 'integer', 'minimum': 1},
                                                  'campaign': {'type': 'string'},
                                                  'channel': {'type': 'string'},
                                                  'objective': {'type': ['string', 'null']},
                                                  'status': {'type': 'string'},
                                                  'budget': {'type': 'number',
                                                             'minimum': 0,
                                                             'multipleOf': Decimal('0.01')},
                                                  'actual_spend': {'type': ['number', 'null'],
                                                                   'minimum': 0,
                                                                   'multipleOf': Decimal('0.01')},
                                                  'currency': {'type': 'string', 'pattern': '^[A-Z]{3}$'},
                                                  'start_date': {'type': 'string', 'format': 'date'},
                                                  'end_date': {'type': 'string', 'format': 'date'},
                                                  'target_audience': {'type': ['string', 'null']},
                                                  'utm_source': {'type': ['string', 'null']},
                                                  'utm_medium': {'type': ['string', 'null']},
                                                  'utm_campaign': {'type': ['string', 'null']},
                                                  'created_at': {'type': 'string',
                                                                 'format': 'date-time',
                                                                 'pattern': 'Z$'},
                                                  'updated_at': {'type': 'string',
                                                                 'format': 'date-time',
                                                                 'pattern': 'Z$'}}}},
 'website_events': {'$schema': 'https://json-schema.org/draft/2020-12/schema',
                    'title': 'website_events',
                    'type': 'array',
                    'items': {'type': 'object',
                              'additionalProperties': False,
                              'required': ['event_id',
                                           'session_id',
                                           'event',
                                           'page',
                                           'timestamp',
                                           'created_at',
                                           'updated_at'],
                              'properties': {'event_id': {'type': 'integer', 'minimum': 1},
                                             'customer_id': {'type': ['integer', 'null'], 'minimum': 1},
                                             'anonymous_id': {'type': ['string', 'null']},
                                             'session_id': {'type': 'string'},
                                             'event': {'type': 'string'},
                                             'page': {'type': 'string'},
                                             'timestamp': {'type': 'string',
                                                           'format': 'date-time',
                                                           'pattern': 'Z$'},
                                             'product_id': {'type': ['integer', 'null'], 'minimum': 1},
                                             'order_id': {'type': ['integer', 'null'], 'minimum': 1},
                                             'device_type': {'type': ['string', 'null']},
                                             'browser': {'type': ['string', 'null']},
                                             'operating_system': {'type': ['string', 'null']},
                                             'traffic_source': {'type': ['string', 'null']},
                                             'utm_source': {'type': ['string', 'null']},
                                             'utm_medium': {'type': ['string', 'null']},
                                             'utm_campaign': {'type': ['string', 'null']},
                                             'country_code': {'type': ['string', 'null']},
                                             'created_at': {'type': 'string',
                                                            'format': 'date-time',
                                                            'pattern': 'Z$'},
                                             'updated_at': {'type': 'string',
                                                            'format': 'date-time',
                                                            'pattern': 'Z$'}}}}}
